defaults:
  - extra_fields # See extra_fields.yaml
  - _self_

args:
  _target_: ribs.archives.CVTArchive
  centroids: ${domain.config.centroids}
  solution_dim: ${domain.config.solution_dim}
  ranges: "${eval:'list(zip(${domain.config.measure_low},${domain.config.measure_high}))'}"
  nearest_neighbors: "sklearn_nn"
  sklearn_nn_kwargs:
    metric: "cosine"
    n_jobs: 16
  dtype: "${get_cls: numpy.float32}"
  extra_fields: ${eval:"dict.get(${..domain_to_extra_fields},'${hydra:runtime.choices.domain}')"}
