_target_: src.domains.lin_proj.FlatLinProj
config:
  solution_dim: 100
  obj_low: 0.0
  obj_high: 1.0
  measure_dim: 2
  measure_low: ${eval:'[-100 / 2 * 5.12, -100 / 2 * 5.12]'}
  measure_high: ${eval:'[100 / 2 * 5.12, 100 / 2 * 5.12]'}
