_target_: src.domains.lin_proj.Rastrigin
config:
  solution_dim: 100
  obj_low: 0.0
  obj_high: 1.0
  measure_dim: 10
  measure_low: ${eval:'[-100 / ${.measure_dim} * 5.12] * ${.measure_dim}'}
  measure_high: ${eval:'[100 / ${.measure_dim} * 5.12] * ${.measure_dim}'}
